export enum ActionsRegisterType{
    SAVE_REGISTER_STUDENT="SAVE_REGISTER_STUDENT",
    SAVE_REGISTER_STUDENT_SUCCESS="SAVE_REGISTER_STUDENT_SUCCESS",
    SAVE_REGISTER_STUDENT_ERROR="SAVE_REGISTER_STUDENT_ERROR",
}